[project]
name = "rc-kronenradanalyse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
    "numpy-stl>=3.2.0",
    "panda>=0.3.1",
    "pandas>=2.3.3",
    "pyglet>=2.1.10",
    "pyqt6>=6.10.0",
    "pyside6>=6.10.0",
    "trimesh>=4.9.0",
]
